import css from "../styles/Home.module.css";
import HeroBanner from "@/component/HeroBanner";
import Layout from "@/component/Layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Layout>
        <div className={css.container}>
          <Head>
            <title>Foodizone</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/assets/Logo.png" />
          </Head>
          <main>
            <HeroBanner />
          </main>
        </div>
      </Layout>
    </>
  );
}
