import css from "../styles/Home.module.css";
import HeroBanner from "@/component/HeroBanner";
import Layout from "@/component/Layout";
import Head from "next/head";
import Services from "@/component/Services";
import { client } from "@/lib/client";
import Menu from "@/component/Menu";

export default function Home({ pizzas }) {
  return (
    <>
      <Layout>
        <div className={css.container}>
          <Head>
            <title>Foodizone</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/assets/Logo.png" />
          </Head>
          <main>
            <HeroBanner />
            <Services />
            <Menu pizzas={pizzas} />
          </main>
        </div>
      </Layout>
    </>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "pizza"]';
  const pizzas = await client.fetch(query);
  return {
    props: {
      pizzas,
    },
  };
};
